"""
User Factory for creating User entities with proper password hashing.

This factory encapsulates the logic for creating User objects,
particularly handling password hashing during user creation.
"""
from werkzeug.security import generate_password_hash
from app.domain.entities import User
from app.domain.roles import Role


class UserFactory:
    """Factory for creating User domain entities."""
    
    @staticmethod
    def create_with_raw_password(full_name: str, email: str, password: str, role: int = 0) -> User:
        """
        Create a User entity with a raw password (which will be hashed).
        
        Args:
            full_name: The user's full name
            email: The user's email address
            password: The raw password (will be hashed)
            role: The user's role (default: UNKNOWN/0)
            
        Returns:
            User: A new User domain entity with hashed password
        """
        password_hash = generate_password_hash(password)
        return User(
            user_id=None,  # Will be generated by database
            full_name=full_name,
            email=email,
            password_hash=password_hash,
            role=role
        )
    
    @staticmethod
    def create_teacher(user_id: int, full_name: str, email: str, password_hash: str) -> User:
        """Create a User with TEACHER role."""
        return User(user_id, full_name, email, password_hash, Role.TEACHER)
    
    @staticmethod
    def create_parent(user_id: int, full_name: str, email: str, password_hash: str) -> User:
        """Create a User with PARENT role."""
        return User(user_id, full_name, email, password_hash, Role.PARENT)
    
    @staticmethod
    def create_admin(user_id: int, full_name: str, email: str, password_hash: str) -> User:
        """Create a User with ADMIN role."""
        return User(user_id, full_name, email, password_hash, Role.ADMIN)
